const citiesWithDelegations = [
  {
    stateId: 1,
    stateName: "Ariana",
    data: [
      "Ariana",
      "Ettadhamen",
      "Kalaat El Andalous",
      "Mnihla",
      "Raoued",
      "Sidi Thabet",
      "Soukra",
    ],
  },
  {
    stateId: 2,
    stateName: "Beja",
    data: [
      "Amdoun",
      "Beja",
      "Goubellat",
      "Majaz al Bab",
      "Nefza",
      "Teboursouk",
      "Testour",
      "Thibar",
    ],
  },
  {
    stateId: 3,
    stateName: "Ben Arous",
    data: [
      "Ben Arous",
      "Bou Mhel el-Bassatine",
      "El Mourouj",
      "Ezzahra",
      "Fouchana",
      "Hammam Chott",
      "Hammam Lif",
      "Mohamedia",
      "Medina Jedida",
      "Megrine",
      "Mornag",
      "Rades",
    ],
  },
  {
    stateId: 4,
    stateName: "Bizerte",
    data: [
      "Bizerte",
      "Djoumime",
      "El Alia",
      "Ghar El Melh",
      "Ghezala",
      "Mateur",
      "Menzel Bourguiba",
      "Menzel Jemil",
      "Ras Jebel",
      "Sejenane",
      "Tinja",
      "Utica",
      "Zarzouna",
    ],
  },
  {
    stateId: 5,
    stateName: "Gabès",
    data: [
      "Gabes",
      "Ghannouch",
      "Hamma",
      "Mareth",
      "Matmata",
      "Menzel Habib",
      "Metouia",
    ],
  },
  {
    stateId: 6,
    stateName: "Gafsa",
    data: [
      "Belkhir",
      "Gafsa",
      "Guetar",
      "Ksar",
      "Mdhila",
      "Metlaoui",
      "Oum Larais",
      "Redeyef",
      "Sened",
      "Sidi Aich",
    ],
  },

  {
    stateId: 8,
    stateName: "Jendouba",
    data: [
      "Ain Draham",
      "Balta",
      "Bou Salem",
      "Fernana",
      "Ghardimaou",
      "Jendouba",
      "Oued Melliz",
      "Tabarka",
    ],
  },
  {
    stateId: 9,
    stateName: "Kairouan",
    data: [
      "Alaâ",
      "Bouhajla",
      "Chebika",
      "Echrarda",
      "Haffouz",
      "Hajeb El Ayoun",
      "Kairouan",
      "Nasrallah",
      "Oueslatia",
      "Sbikha",
    ],
  },
  {
    stateId: 10,
    stateName: "Kasserine",
    data: [
      "Ayoun",
      "Ezzouhour",
      "Feriana",
      "Foussana",
      "Hassi El Ferid",
      "Hidra",
      "Jedeliane",
      "Kasserine",
      "Magel Bel Abbes",
      "Sbeitla",
      "Sbiba",
      "Thala",
    ],
  },
  {
    stateId: 11,
    stateName: "Kebili",
    data: [
      "Douz North",
      "Douz South",
      "Faouar",
      "Kebili North",
      "Kebili South",
      "Souk El Ahed",
    ],
  },
  {
    stateId: 12,
    stateName: "Kef",
    data: [
      "Dahmani",
      "Es Sers",
      "Jerissa",
      "Kalaa Khasbat",
      "Kalaat Senane",
      "Kef East",
      "Kef West",
      "Ksour",
      "Nebeur",
      "Sakiet Sidi Youssef",
      "Tajerouine",
      "Touiref",
    ],
  },
  {
    stateId: 13,
    stateName: "Mahdia",
    data: [
      "Boumerdes",
      "Chebba",
      "Chorbane",
      "El Djem",
      "Hbira",
      "Ksour Essef",
      "Mahdia",
      "Melloulech",
      "Ouled Chamekh",
      "Sidi Alouane",
      "Souassi",
    ],
  },
  {
    stateId: 14,
    stateName: "Manouba",
    data: [
      "Borj El Amri",
      "Douar Hicher",
      "El Battan",
      "Jedaida",
      "Manouba",
      "Mornaguia",
      "Oued Ellil",
      "Tebourba",
    ],
  },
  {
    stateId: 15,
    stateName: "Medenine",
    data: [
      "Ben Gardane",
      "Beni Khedache",
      "Djerba Ajim",
      "Djerba Midoun",
      "Djerba Houmt Souk",
      "Medenine North",
      "Medenine South",
      "Sidi Makhlouf",
      "Zarzis",
    ],
  },
  {
    stateId: 16,
    stateName: "Monastir",
    data: [
      "Bekalta",
      "Bembla",
      "Beni Hassen",
      "Jammel",
      "Ksar Hellal",
      "Ksibet El Mediouni",
      "Moknine",
      "Monastir",
      "Ouerdanine",
      "Sahline",
      "Sayada-Lamta-Bou Hjar",
      "Teboulba",
      "Zeramdine",
    ],
  },
  {
    stateId: 17,
    stateName: "Nabeul",
    data: [
      "Beni Khalled",
      "Beni Khiar",
      "Bou Argoub",
      "Dar Chaabane El Fehri",
      "El Mida",
      "Grombalia",
      "Hammam Ghezaz",
      "Hammamet",
      "Haouaria",
      "Kelibia",
      "Korba",
      "Menzel Bouzelfa",
      "Menzel Temime",
      "Nabeul",
      "Soliman",
      "Takelsa",
    ],
  },
  {
    stateId: 18,
    stateName: "Sfax",
    data: [
      "Agareb",
      "Bir Ali Ben Khelifa",
      "El Amra",
      "El Ghraiba",
      "Hencha",
      "Jebeniana",
      "Kerkennah",
      "Mahres",
      "Menzel Chaker",
      "Sakiet Eddaier",
      "Sakiet Ezzit",
      "Sfax Medina",
      "Sfax West",
      "Sfax South",
      "Skhira",
      "Thyna",
    ],
  },
  {
    stateId: 19,
    stateName: "Sidi Bouzid",
    data: [
      "Bir El Hfay",
      "Jelma",
      "Mazzouna",
      "Meknassi",
      "Menzel Bouzaiene",
      "Ouled Haffouz",
      "Regueb",
      "Sabalat Ouled Asker",
      "Sidi Ali Ben Aoun",
      "Sidi Bouzid East",
      "Sidi Bouzid West",
      "Souk Jedid",
    ],
  },
  {
    stateId: 20,
    stateName: "Siliana",
    data: [
      "Bargou",
      "Bouarada",
      "El Aroussa",
      "El Krib",
      "Gaafour",
      "Kesra",
      "Makthar",
      "Rouhia",
      "Sidi Bourouis",
      "Siliana North",
      "Siliana South",
    ],
  },
  {
    stateId: 21,
    stateName: "Sousse",
    data: [
      "Akouda",
      "Bouficha",
      "Enfidha",
      "Hammam Sousse",
      "Hergla",
      "Kalaa Kebira",
      "Kalaa Sghira",
      "Kondar",
      "M'Saken",
      "Sidi Bou Ali",
      "Sidi El Heni",
      "Sousse Jaouhara",
      "Sousse Medina",
      "Sousse Riadh",
      "Sousse Sidi Abdelhamid",
      "Zaouiet Ksibet Thrayet",
    ],
  },
  {
    stateId: 22,
    stateName: "Tataouine",
    data: ["Bir Lahmar", "Dhiba", "Ghomrassen", "Remada", "Samar", "Tataouine"],
  },
  {
    stateId: 23,
    stateName: "Tozeur",
    data: ["Degueche", "Hazoua", "Nefta", "Tamaghza", "Tozeur"],
  },
  {
    stateId: 24,
    stateName: "Tunis",
    data: [
      "Bab Bhar",
      "Bab Souika",
      "Carthage",
      "Cité El Khadra",
      "Djebel Djelloud",
      "El-Haraïria",
      "El Kabaria",
      "El Menzah",
      "El Omrane",
      "El Omrane Supérieur",
      "El Ouardia",
      "Ettahrir",
      "Ezzouhour",
      "La Goulette",
      "La Marsa",
      "Le Bardo",
      "Le Kram",
      "Medina",
      "Sidi El Béchir",
      "Sidi Hassine",
      "Sijoumi",
      "Zaghouan",
    ],
  },
  {
    stateId: 25,
    stateName: "Zaghouan",
    data: ["Bir Mchergua", "Fahs", "Nadhour", "Saouaf", "Zaghouan", "Zriba"],
  },
];
export const stateOptions = citiesWithDelegations.map((c) => {
  return { label: c.stateName, value: c.stateName };
});
export default citiesWithDelegations;
